### ISSUE TITLE
_make_xselect_commands always uses ./ as evtdir

### ISSUE THREAD

**Issue by bigfalke** [NuSTAR/nustar-gen-utils#41]
In the other _make_xselect* functions in 'wrappres.py', the event directory is read from via os.path.dirname(infile), but in '_make_xselect_commands' it just always uses './'. 
I would suggest to change that to be consistent with the other functions, and to be able to use files outside of the path.
Not sure if I can create a PR for that when I'm not a contributer?

**Comment by bwgref** [comment]
You're only not a contributor because you haven't made a PR yet ;) And yes, I think this is related to #38 where I haven't been super careful about maintaining any kind of consistency between paths (some things get tested and adjusted more than others).

Feel free to open a PR for this one.

**Comment by bwgref** [comment]
Closed in #42
