### ISSUE TITLE
make_image broken?

### ISSUE THREAD

**Issue by matteobachetti** [NuSTAR/nustar-gen-utils#53]
Using nustar-gen-utils for images. Following the notebook OptimalRadius_Example, I get the following error:
```
   ...: full_range = make_image(infile, elow=3, ehigh=80, clobber=True)
   ...: 
   ...: 
rm: cannot remove '(....)6_chu12_N_cl_3to80keV.fits': No such file or directory
                         **  XSELECT V2.4k  **
!> Enter session name >[xsel663358] session1
 Command not found; type ? for a command listing
!session1:SUZAKU > read events
!> Enter the Event file dir >[663358_tmp_nuscreen]
The directory 663358_tmp_nuscreen/ doesn't exist
session1:SUZAKU > 
session1:SUZAKU
```

**Comment by bwgref** [comment]
After chat with @matteobachetti on Slack, sounds like file I/O needs to be a bit more robust using os.path.abspath where appropriate to make sure that things come through with the actual full paths even if you just give the short pathname to a file (i.e., if you're already in the working directory).
