### ISSUE TITLE
Region Package installation problem

### ISSUE THREAD

**Issue by qwert3434** [NuSTAR/nustar-gen-utils#99]
Problem: Installing the region package through the "requirements.txt" will cause an issue that conda cannot find region package 0.5 and install region package 0.6 instead.

To fix it: run "pip install regions==0.5" after the requirements.txt

**Comment by bwgref** [comment]
This works if you have conda-forge as the primary channel. I've updated the README installation files to reflect this to make sure that people are using conda-forge and not just vanilla conda.
